version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:3000"    # host:container
    env_file: .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5433:5432"
    volumes:
      - db_data_redis:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  db_data_redis: